# Generated by Django 3.0.6 on 2020-07-19 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstName')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastName')),
                ('sex', models.BooleanField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('born', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
